### ISSUE TITLE
After several epochs, the loss turns into NaN.

### ISSUE THREAD

**Issue by hzlhzlhzlhzl** [Vencent-Won/SGGRL#2]
I appreciate the work you've put into this project and would be grateful for your assistance in resolving this problem. I am encountering an issue where the loss turns into NaN after several epochs, regardless of whether I am working on a classification or regression task.
![1704888341140](https://github.com/Vencent-Won/SGGRL/assets/94671385/6c2f862e-9e62-4d6a-a1d1-5674491ae234)

**Comment by hzlhzlhzlhzl** [comment]
Traceback (most recent call last):
  File "main.py", line 322, in <module>
    main(arg)
  File "main.py", line 291, in main
    val_result, val_all_loss, val_lab_loss, val_cl_loss, model = val(args, model, scaler, val_sampler, seq_data,
  File "/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "main.py", line 136, in val
    result = eval_rocauc(input_dict)['rocauc']
  File "/SGGRL/utils/evaluate.py", line 23, in eval_rocauc
    rocauc_list.append(roc_auc_score(y_true[is_labeled, i], y_pred[is_labeled, i]))
  File "/envs/geo3d/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/geo3d/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 605, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "/geo3d/lib/python3.8/site-packages/sklearn/utils/validation.py", line 959, in check_array
    _assert_all_finite(
  File "/envs/geo3d/lib/python3.8/site-packages/sklearn/utils/validation.py", line 124, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/geo3d/lib/python3.8/site-packages/sklearn/utils/validation.py", line 173, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

**Comment by Overthat** [comment]
It is the dimension error problem of [Lower batch size in the last iteration](https://stackoverflow.com/questions/74713084/lower-batch-size-in-the-last-iteration-of-first-training-epoch-than-the-other-it) in `main.py: 87`. Variable `idx` only contains 1 element in the last epoch.

More specificly in the file `multimodal.py: 180`, `sim_matrix.sum(dim=1)`equals to `pos_sim` when `batch size = 1`, which causes a division by zero in the denominator.

**Comment by Vencent-Won** [comment]
@hzlhzlhzlhzl I think the reponse of @Overthat can help you.
